### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by gjhkael** [WZBSocialScienceCenter/pdftabextract#1]
Can this project run on windows？ And this project can recognize numbers from image？

**Comment by internaut** [comment]
**Please do not use the issue tracker for general questions. You can rather contact me directly.**

pdftabextract can be used on Windows. However, I'm not sure if you will be able to install tools like *pdftohtml* (from poppler-utils on Linux systems) to convert "sandwich PDFs" to XML files.

pdftabextract *does not* implement Optical Character Recognition (OCR) itself and hence it does not recognize numbers! You will need to do the OCR processing beforehand with software like FineReader or tesseract and create "sandwich PDFs" with the scanned images and recognized text.
