### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by monkeydust** [WZBSocialScienceCenter/pdftabextract#12]
Can this be used to extract tables from something like this through Juypter Notebook?

http://www.tradeweb.com/uploadedFiles/Tradweb/Content/About_Us/02.21.2018%20-%20Tradeweb%20Markets%20Quarterly%20Activity%20Report%20-%204Q17.pdf

Thanks

**Comment by internaut** [comment]
Github's issues page is not a Q&A.
