### ISSUE TITLE
Please help me.

### ISSUE THREAD

**Issue by eaglecoder1023** [WZBSocialScienceCenter/pdftabextract#15]
I want this table to be recognized using pdftabextract.
![roi_1_](https://user-images.githubusercontent.com/36554606/40676302-08f5df4c-6383-11e8-80a2-7927bfe48e21.jpg)
I converted that to searchable pdf using tesseract and followed every step in this tutorial
https://datascience.blog.wzb.eu/2017/02/16/data-mining-ocr-pdfs-using-pdftabextract-to-liberate-tabular-data-from-scanned-documents/
And I got this result
[output.xlsx](https://github.com/WZBSocialScienceCenter/pdftabextract/files/2049861/output.xlsx)
I want to improve result as much similar as image.
Please help me.

**Comment by internaut** [comment]
**Closed. Please do not abuse the issue tracker for such requests.**

Your table is well structured enough to be parsed without pdftabextract. Simply use tesseract for the OCR and then `pdftotext` (with the `-layout` parameter) from poppler-utils for converting it to plain text. Write a simple Python script to parse the text.
