### ISSUE TITLE
jpeg8.dll does not exist

### ISSUE THREAD

**Issue by aborruso** [WZBSocialScienceCenter/pdftabextract#2]
Hi,
when I run pdftohtml I have an error because I do not have on my system (Win 10 64bit) jpeg8.dll.

How to solve this problem?

Thank you

**Comment by internaut** [comment]
Sorry, I'm not familiar with poppler-utils/pdftohtml on Windows. I have only installed it on Linux and OSX systems. You should post your problem in the respective poppler-utils/pdftohtml mailinglists or forums, pdftabextract has nothing to do with that.
