### ISSUE TITLE
Logger file missing

### ISSUE THREAD

**Issue by pcakhilnadh** [WZBSocialScienceCenter/pdftabextract#20]
It seems logger file is missing 

> from pdftabextract import logger

in clustering.py

**Comment by internaut** [comment]
No, it's not a file but an object in `__init__.py` and it's here: 

https://github.com/WZBSocialScienceCenter/pdftabextract/blob/ce557748a5f7b7ab8e51753cc1cdd55d81dea2dc/pdftabextract/__init__.py#L9
