### ISSUE TITLE
`Poppler` installation on windows

### ISSUE THREAD

**Issue by aiern** [WZBSocialScienceCenter/pdftabextract#21]
I've been trying to install Poppler to execute the first line of code pdf2html, using "pip install python-poppler-qt5" also tried conda installation but failed. Tried to add the source files to my anaconda/lib/site-packages directory also failed. Please could someone tell me how to get poppler up and running on windows?

**Comment by internaut** [comment]
This is not an issue related with pdftabextract so I won't discuss this here on the "issues" list. Honestly, there are plenty of results when you google for it.
