### ISSUE TITLE
pdftohtml not generating image tag in XML file

### ISSUE THREAD

**Issue by tonivss** [WZBSocialScienceCenter/pdftabextract#22]
When generating a XML file via pdftohtml like 
`pdftohtml -c -hidden -xml input.pdf output.xml`
there is no image tag in the XML file (also this command is only generating a XML file, PNGs will not be generated). 
I have followed all the steps mentioned on your blog post but the code does not execute properly because at 
`imgflebasename = p['image'][:p['image'].rindex('.')]`
no images are found and therefore there is no attribute `rindex`.

**Comment by internaut** [comment]
`pdftohtml` is not part of pdftabextract. It's part of the poppler-utils package. I can't give support on that.
