### ISSUE TITLE
Use pdftabextract convert pdf which is converted by a picture

### ISSUE THREAD

**Issue by CapitaineNemo** [WZBSocialScienceCenter/pdftabextract#7]
Hi, I try to convert a pdf to excel, but it failed. It is a table in a picture. I convert the picture into pdf , then I use the code to convert. It failed.  So could you tell me what kind of pdf can be converted?

**Comment by internaut** [comment]
pdftabextract is *not* an OCR software but a tool to help extract tabular information from already OCR-processed PDFs. You need to use OCR software like Abbyy FineReader first to recognize the text in your page(s).
