### ISSUE TITLE
pdftabextract does not label an text boxes

### ISSUE THREAD

**Issue by jenniferzhu** [WZBSocialScienceCenter/pdftabextract#9]
pdftabextract does not label an text boxes in the scanned PDF I have. What could be possible reason?

**Comment by jenniferzhu** [comment]
Also the pdf2xml-viewer does not allow load any files. i.e. both "load" buttons do not work...

**Comment by internaut** [comment]
Your PDF must be OCR processed, not just scanned. Did you do that?

pdftabextract is *not* an OCR software. It is a set of tools to help extract tabular information from already OCR processed PDFs.

**Comment by skadambala** [comment]
I have processed my pdf with ABBYY Fine Reader and analyzed and exported as  somename.pdf . Then ran command pdftohtml -c -hidden -xml somename.pdf somename.pdf.xml.

This created xml file but not images and also the generated xml has  text tags but do not have image tags. 

What could be the possible reason ? I doubt if i missed doing something with the scanned pdf on FineReader.

**Comment by internaut** [comment]
Sorry, this is not a help site for poppler-utils (pdf* commands).

Anyway, you may see the list of images inside your PDF with  `pdfimages -list FILE.pdf`. If there are none listed, then something's wrong with the PDF.
You may then extract those images also with `pdfimages -p FILE.pdf IMAGE_PREFIX`. You can assign the image files to the respective pages then with the `use_images` parameter of the `parse_pages` function in the `common` module.

**Comment by skadambala** [comment]
@internaut 
I was able to figure out the issue. When i ran the same command on Linux, images were created. On Mac, xml was created but not images.      
There is some OS dependencies. 

Thanks for you reply.
